<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Data\Jitendex.Data.csproj" />
    <ProjectReference Include="..\Data.Tatoeba\Jitendex.Data.Tatoeba.csproj" />
    <ProjectReference Include="..\Dto\Jitendex.Dto.csproj" />
    <ProjectReference Include="..\EdrdgDictionaryArchive\Jitendex.EdrdgDictionaryArchive.csproj" />
    <ProjectReference Include="..\Import\Jitendex.Import.csproj" />
    <ProjectReference Include="..\..\Libraries\MinimalJsonDiff\Jitendex.MinimalJsonDiff\Jitendex.MinimalJsonDiff.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Collections.Immutable" />
  </ItemGroup>
</Project>