/*
Copyright (c) 2025-2026 Stephen Kraus
SPDX-License-Identifier: AGPL-3.0-or-later

This file is part of Jitendex.

Jitendex is free software: you can redistribute it and/or modify it under the terms of
the GNU Affero General Public License as published by the Free Software Foundation,
either version 3 of the License or (at your option) any later version.

Jitendex is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with Jitendex.
If not, see <https://www.gnu.org/licenses/>.
*/

using Jitendex.Data;
using Jitendex.Data.Tatoeba;
using Jitendex.Data.Tatoeba.Entities;
using Microsoft.EntityFrameworkCore;

namespace Jitendex.Forks.Tatoeba.Services;

internal sealed class DatabaseCopyService(TatoebaForkContext context)
{
    public void CopyDataFromTatoeba()
    {
        context.AttachDatabase(DatabaseFile.Tatoeba);
        context.Database.ExecuteSqlRaw(TransferCommandText);
    }

    private const string Schema = nameof(DatabaseFile.Tatoeba);

    /// <remarks>
    /// This command text was generated by a query located in the
    /// `transfer_command_builder.sql` file in the Jitendex directory `~/Scripts`.
    /// </remarks>
    private const string TransferCommandText =
        $"""
        INSERT INTO "{nameof(FileHeader)}"
             ( "{nameof(FileHeader.Id)}"
             , "{nameof(FileHeader.Date)}")
        SELECT "{nameof(FileHeader.Id)}"
             , "{nameof(FileHeader.Date)}"
          FROM "{Schema}"."{nameof(FileHeader)}";

        INSERT INTO "{nameof(Sequence)}"
             ( "{nameof(Sequence.Id)}"
             , "{nameof(Sequence.OriginFileId)}")
        SELECT "{nameof(Sequence.Id)}"
             , "{nameof(Sequence.OriginFileId)}"
          FROM "{Schema}"."{nameof(Sequence)}";

        INSERT INTO "{nameof(Example)}"
             ( "{nameof(Example.Id)}"
             , "{nameof(Example.Text)}")
        SELECT "{nameof(Example.Id)}"
             , "{nameof(Example.Text)}"
          FROM "{Schema}"."{nameof(Example)}";

        INSERT INTO "{nameof(Revision)}"
             ( "{nameof(Revision.SequenceId)}"
             , "{nameof(Revision.Number)}"
             , "{nameof(Revision.FileHeaderId)}"
             , "{nameof(Revision.IsPriority)}"
             , "{nameof(Revision.DiffJson)}")
        SELECT "{nameof(Revision.SequenceId)}"
             , "{nameof(Revision.Number)}"
             , "{nameof(Revision.FileHeaderId)}"
             , "{nameof(Revision.IsPriority)}"
             , "{nameof(Revision.DiffJson)}"
          FROM "{Schema}"."{nameof(Revision)}";

        INSERT INTO "{nameof(Segmentation)}"
             ( "{nameof(Segmentation.ExampleId)}"
             , "{nameof(Segmentation.Order)}"
             , "{nameof(Segmentation.TranslationId)}")
        SELECT "{nameof(Segmentation.ExampleId)}"
             , "{nameof(Segmentation.Order)}"
             , "{nameof(Segmentation.TranslationId)}"
          FROM "{Schema}"."{nameof(Segmentation)}";

       INSERT INTO "{nameof(Token)}"
            ( "{nameof(Token.ExampleId)}"
            , "{nameof(Token.SegmentationOrder)}"
            , "{nameof(Token.Order)}"
            , "{nameof(Token.Headword)}"
            , "{nameof(Token.Reading)}"
            , "{nameof(Token.EntryId)}"
            , "{nameof(Token.SenseNumber)}"
            , "{nameof(Token.SentenceForm)}"
            , "{nameof(Token.IsPriority)}")
       SELECT "{nameof(Token.ExampleId)}"
            , "{nameof(Token.SegmentationOrder)}"
            , "{nameof(Token.Order)}"
            , "{nameof(Token.Headword)}"
            , "{nameof(Token.Reading)}"
            , "{nameof(Token.EntryId)}"
            , "{nameof(Token.SenseNumber)}"
            , "{nameof(Token.SentenceForm)}"
            , "{nameof(Token.IsPriority)}"
         FROM "{Schema}"."{nameof(Token)}";
       """;
}
