/*
Copyright (c) 2025-2026 Stephen Kraus
SPDX-License-Identifier: AGPL-3.0-or-later

This file is part of Jitendex.

Jitendex is free software: you can redistribute it and/or modify it under the terms of
the GNU Affero General Public License as published by the Free Software Foundation,
either version 3 of the License or (at your option) any later version.

Jitendex is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with Jitendex.
If not, see <https://www.gnu.org/licenses/>.
*/

using Jitendex.Data;
using Jitendex.Data.JMdict;
using Jitendex.Data.JMdict.Entities;
using Jitendex.Data.JMdict.Entities.EntryChildren;
using Jitendex.Data.JMdict.Entities.EntryChildren.KanjiFormChildren;
using Jitendex.Data.JMdict.Entities.EntryChildren.ReadingChildren;
using Jitendex.Data.JMdict.Entities.EntryChildren.SenseChildren;
using Microsoft.EntityFrameworkCore;

namespace Jitendex.Forks.JMdict.Services;

internal sealed class DatabaseCopyService(JMdictForkContext context)
{
    public void CopyDataFromJmdict()
    {
        context.AttachDatabase(DatabaseFile.JMdict);
        context.Database.ExecuteSqlRaw(TransferCommandText);
    }

    private const string Schema = nameof(DatabaseFile.JMdict);

    // This command text was generated by a query located in the
    // `transfer_command_builder.sql` file in the Jitendex directory `~/Scripts`.
    private const string TransferCommandText =
        $"""
        INSERT INTO "{nameof(FileHeader)}"
             ( "{nameof(FileHeader.Id)}"
             , "{nameof(FileHeader.Date)}")
        SELECT "{nameof(FileHeader.Id)}"
             , "{nameof(FileHeader.Date)}"
          FROM "{Schema}"."{nameof(FileHeader)}";

        INSERT INTO "{nameof(CrossReferenceType)}"
             ( "{nameof(CrossReferenceType.Name)}"
             , "{nameof(CrossReferenceType.OriginFileId)}")
        SELECT "{nameof(CrossReferenceType.Name)}"
             , "{nameof(CrossReferenceType.OriginFileId)}"
          FROM "{Schema}"."{nameof(CrossReferenceType)}";

        INSERT INTO "{nameof(DialectTag)}"
             ( "{nameof(DialectTag.Name)}"
             , "{nameof(DialectTag.OriginFileId)}")
        SELECT "{nameof(DialectTag.Name)}"
             , "{nameof(DialectTag.OriginFileId)}"
          FROM "{Schema}"."{nameof(DialectTag)}";

        INSERT INTO "{nameof(FieldTag)}"
             ( "{nameof(FieldTag.Name)}"
             , "{nameof(FieldTag.OriginFileId)}")
        SELECT "{nameof(FieldTag.Name)}"
             , "{nameof(FieldTag.OriginFileId)}"
          FROM "{Schema}"."{nameof(FieldTag)}";

        INSERT INTO "{nameof(GlossTypeTag)}"
             ( "{nameof(GlossTypeTag.Name)}"
             , "{nameof(GlossTypeTag.OriginFileId)}")
        SELECT "{nameof(GlossTypeTag.Name)}"
             , "{nameof(GlossTypeTag.OriginFileId)}"
          FROM "{Schema}"."{nameof(GlossTypeTag)}";

        INSERT INTO "{nameof(KanjiFormInfoTag)}"
             ( "{nameof(KanjiFormInfoTag.Name)}"
             , "{nameof(KanjiFormInfoTag.OriginFileId)}")
        SELECT "{nameof(KanjiFormInfoTag.Name)}"
             , "{nameof(KanjiFormInfoTag.OriginFileId)}"
          FROM "{Schema}"."{nameof(KanjiFormInfoTag)}";

        INSERT INTO "{nameof(Language)}"
             ( "{nameof(Language.Name)}"
             , "{nameof(Language.OriginFileId)}")
        SELECT "{nameof(Language.Name)}"
             , "{nameof(Language.OriginFileId)}"
          FROM "{Schema}"."{nameof(Language)}";

        INSERT INTO "{nameof(LanguageSourceType)}"
             ( "{nameof(LanguageSourceType.Name)}"
             , "{nameof(LanguageSourceType.OriginFileId)}")
        SELECT "{nameof(LanguageSourceType.Name)}"
             , "{nameof(LanguageSourceType.OriginFileId)}"
          FROM "{Schema}"."{nameof(LanguageSourceType)}";

        INSERT INTO "{nameof(MiscTag)}"
             ( "{nameof(MiscTag.Name)}"
             , "{nameof(MiscTag.OriginFileId)}")
        SELECT "{nameof(MiscTag.Name)}"
             , "{nameof(MiscTag.OriginFileId)}"
          FROM "{Schema}"."{nameof(MiscTag)}";

        INSERT INTO "{nameof(PartOfSpeechTag)}"
             ( "{nameof(PartOfSpeechTag.Name)}"
             , "{nameof(PartOfSpeechTag.OriginFileId)}")
        SELECT "{nameof(PartOfSpeechTag.Name)}"
             , "{nameof(PartOfSpeechTag.OriginFileId)}"
          FROM "{Schema}"."{nameof(PartOfSpeechTag)}";

        INSERT INTO "{nameof(PriorityTag)}"
             ( "{nameof(PriorityTag.Name)}"
             , "{nameof(PriorityTag.OriginFileId)}")
        SELECT "{nameof(PriorityTag.Name)}"
             , "{nameof(PriorityTag.OriginFileId)}"
          FROM "{Schema}"."{nameof(PriorityTag)}";

        INSERT INTO "{nameof(ReadingInfoTag)}"
             ( "{nameof(ReadingInfoTag.Name)}"
             , "{nameof(ReadingInfoTag.OriginFileId)}")
        SELECT "{nameof(ReadingInfoTag.Name)}"
             , "{nameof(ReadingInfoTag.OriginFileId)}"
          FROM "{Schema}"."{nameof(ReadingInfoTag)}";

        INSERT INTO "{nameof(Sequence)}"
             ( "{nameof(Sequence.Id)}"
             , "{nameof(Sequence.OriginFileId)}")
        SELECT "{nameof(Sequence.Id)}"
             , "{nameof(Sequence.OriginFileId)}"
          FROM "{Schema}"."{nameof(Sequence)}";

        INSERT INTO "{nameof(Entry)}"
             ( "{nameof(Entry.Id)}")
        SELECT "{nameof(Entry.Id)}"
          FROM "{Schema}"."{nameof(Entry)}";

        INSERT INTO "{nameof(Revision)}"
             ( "{nameof(Revision.SequenceId)}"
             , "{nameof(Revision.FileHeaderId)}"
             , "{nameof(Revision.DiffJson)}")
        SELECT "{nameof(Revision.SequenceId)}"
             , "{nameof(Revision.FileHeaderId)}"
             , "{nameof(Revision.DiffJson)}"
          FROM "{Schema}"."{nameof(Revision)}";

        INSERT INTO "{nameof(KanjiForm)}"
             ( "{nameof(KanjiForm.EntryId)}"
             , "{nameof(KanjiForm.Order)}"
             , "{nameof(KanjiForm.Text)}")
        SELECT "{nameof(KanjiForm.EntryId)}"
             , "{nameof(KanjiForm.Order)}"
             , "{nameof(KanjiForm.Text)}"
          FROM "{Schema}"."{nameof(KanjiForm)}";

        INSERT INTO "{nameof(Reading)}"
             ( "{nameof(Reading.EntryId)}"
             , "{nameof(Reading.Order)}"
             , "{nameof(Reading.Text)}"
             , "{nameof(Reading.NoKanji)}")
        SELECT "{nameof(Reading.EntryId)}"
             , "{nameof(Reading.Order)}"
             , "{nameof(Reading.Text)}"
             , "{nameof(Reading.NoKanji)}"
          FROM "{Schema}"."{nameof(Reading)}";

        INSERT INTO "{nameof(Sense)}"
             ( "{nameof(Sense.EntryId)}"
             , "{nameof(Sense.Order)}")
        SELECT "{nameof(Sense.EntryId)}"
             , "{nameof(Sense.Order)}"
          FROM "{Schema}"."{nameof(Sense)}";

        INSERT INTO "{nameof(KanjiFormInfo)}"
             ( "{nameof(KanjiFormInfo.EntryId)}"
             , "{nameof(KanjiFormInfo.KanjiFormOrder)}"
             , "{nameof(KanjiFormInfo.Order)}"
             , "{nameof(KanjiFormInfo.TagName)}")
        SELECT "{nameof(KanjiFormInfo.EntryId)}"
             , "{nameof(KanjiFormInfo.KanjiFormOrder)}"
             , "{nameof(KanjiFormInfo.Order)}"
             , "{nameof(KanjiFormInfo.TagName)}"
          FROM "{Schema}"."{nameof(KanjiFormInfo)}";

        INSERT INTO "{nameof(KanjiFormPriority)}"
             ( "{nameof(KanjiFormPriority.EntryId)}"
             , "{nameof(KanjiFormPriority.KanjiFormOrder)}"
             , "{nameof(KanjiFormPriority.Order)}"
             , "{nameof(KanjiFormPriority.TagName)}")
        SELECT "{nameof(KanjiFormPriority.EntryId)}"
             , "{nameof(KanjiFormPriority.KanjiFormOrder)}"
             , "{nameof(KanjiFormPriority.Order)}"
             , "{nameof(KanjiFormPriority.TagName)}"
          FROM "{Schema}"."{nameof(KanjiFormPriority)}";

        INSERT INTO "{nameof(ReadingInfo)}"
             ( "{nameof(ReadingInfo.EntryId)}"
             , "{nameof(ReadingInfo.ReadingOrder)}"
             , "{nameof(ReadingInfo.Order)}"
             , "{nameof(ReadingInfo.TagName)}")
        SELECT "{nameof(ReadingInfo.EntryId)}"
             , "{nameof(ReadingInfo.ReadingOrder)}"
             , "{nameof(ReadingInfo.Order)}"
             , "{nameof(ReadingInfo.TagName)}"
          FROM "{Schema}"."{nameof(ReadingInfo)}";

        INSERT INTO "{nameof(ReadingPriority)}"
             ( "{nameof(ReadingPriority.EntryId)}"
             , "{nameof(ReadingPriority.ReadingOrder)}"
             , "{nameof(ReadingPriority.Order)}"
             , "{nameof(ReadingPriority.TagName)}")
        SELECT "{nameof(ReadingPriority.EntryId)}"
             , "{nameof(ReadingPriority.ReadingOrder)}"
             , "{nameof(ReadingPriority.Order)}"
             , "{nameof(ReadingPriority.TagName)}"
          FROM "{Schema}"."{nameof(ReadingPriority)}";

        INSERT INTO "{nameof(Restriction)}"
             ( "{nameof(Restriction.EntryId)}"
             , "{nameof(Restriction.ReadingOrder)}"
             , "{nameof(Restriction.Order)}"
             , "{nameof(Restriction.KanjiFormText)}")
        SELECT "{nameof(Restriction.EntryId)}"
             , "{nameof(Restriction.ReadingOrder)}"
             , "{nameof(Restriction.Order)}"
             , "{nameof(Restriction.KanjiFormText)}"
          FROM "{Schema}"."{nameof(Restriction)}";

        INSERT INTO "{nameof(CrossReference)}"
             ( "{nameof(CrossReference.EntryId)}"
             , "{nameof(CrossReference.SenseOrder)}"
             , "{nameof(CrossReference.Order)}"
             , "{nameof(CrossReference.TypeName)}"
             , "{nameof(CrossReference.Text)}")
        SELECT "{nameof(CrossReference.EntryId)}"
             , "{nameof(CrossReference.SenseOrder)}"
             , "{nameof(CrossReference.Order)}"
             , "{nameof(CrossReference.TypeName)}"
             , "{nameof(CrossReference.Text)}"
          FROM "{Schema}"."{nameof(CrossReference)}";

        INSERT INTO "{nameof(Dialect)}"
             ( "{nameof(Dialect.EntryId)}"
             , "{nameof(Dialect.SenseOrder)}"
             , "{nameof(Dialect.Order)}"
             , "{nameof(Dialect.TagName)}")
        SELECT "{nameof(Dialect.EntryId)}"
             , "{nameof(Dialect.SenseOrder)}"
             , "{nameof(Dialect.Order)}"
             , "{nameof(Dialect.TagName)}"
          FROM "{Schema}"."{nameof(Dialect)}";

        INSERT INTO "{nameof(Field)}"
             ( "{nameof(Field.EntryId)}"
             , "{nameof(Field.SenseOrder)}"
             , "{nameof(Field.Order)}"
             , "{nameof(Field.TagName)}")
        SELECT "{nameof(Field.EntryId)}"
             , "{nameof(Field.SenseOrder)}"
             , "{nameof(Field.Order)}"
             , "{nameof(Field.TagName)}"
          FROM "{Schema}"."{nameof(Field)}";

        INSERT INTO "{nameof(Gloss)}"
             ( "{nameof(Gloss.EntryId)}"
             , "{nameof(Gloss.SenseOrder)}"
             , "{nameof(Gloss.Order)}"
             , "{nameof(Gloss.Text)}")
        SELECT "{nameof(Gloss.EntryId)}"
             , "{nameof(Gloss.SenseOrder)}"
             , "{nameof(Gloss.Order)}"
             , "{nameof(Gloss.Text)}"
          FROM "{Schema}"."{nameof(Gloss)}";

        INSERT INTO "{nameof(GlossType)}"
             ( "{nameof(GlossType.EntryId)}"
             , "{nameof(GlossType.SenseOrder)}"
             , "{nameof(GlossType.GlossOrder)}"
             , "{nameof(GlossType.TagName)}")
        SELECT "{nameof(GlossType.EntryId)}"
             , "{nameof(GlossType.SenseOrder)}"
             , "{nameof(GlossType.GlossOrder)}"
             , "{nameof(GlossType.TagName)}"
          FROM "{Schema}"."{nameof(GlossType)}";

        INSERT INTO "{nameof(KanjiFormRestriction)}"
             ( "{nameof(KanjiFormRestriction.EntryId)}"
             , "{nameof(KanjiFormRestriction.SenseOrder)}"
             , "{nameof(KanjiFormRestriction.Order)}"
             , "{nameof(KanjiFormRestriction.KanjiFormText)}")
        SELECT "{nameof(KanjiFormRestriction.EntryId)}"
             , "{nameof(KanjiFormRestriction.SenseOrder)}"
             , "{nameof(KanjiFormRestriction.Order)}"
             , "{nameof(KanjiFormRestriction.KanjiFormText)}"
          FROM "{Schema}"."{nameof(KanjiFormRestriction)}";

        INSERT INTO "{nameof(LanguageSource)}"
             ( "{nameof(LanguageSource.EntryId)}"
             , "{nameof(LanguageSource.SenseOrder)}"
             , "{nameof(LanguageSource.Order)}"
             , "{nameof(LanguageSource.Text)}"
             , "{nameof(LanguageSource.LanguageCode)}"
             , "{nameof(LanguageSource.TypeName)}"
             , "{nameof(LanguageSource.IsWasei)}")
        SELECT "{nameof(LanguageSource.EntryId)}"
             , "{nameof(LanguageSource.SenseOrder)}"
             , "{nameof(LanguageSource.Order)}"
             , "{nameof(LanguageSource.Text)}"
             , "{nameof(LanguageSource.LanguageCode)}"
             , "{nameof(LanguageSource.TypeName)}"
             , "{nameof(LanguageSource.IsWasei)}"
          FROM "{Schema}"."{nameof(LanguageSource)}";

        INSERT INTO "{nameof(Misc)}"
             ( "{nameof(Misc.EntryId)}"
             , "{nameof(Misc.SenseOrder)}"
             , "{nameof(Misc.Order)}"
             , "{nameof(Misc.TagName)}")
        SELECT "{nameof(Misc.EntryId)}"
             , "{nameof(Misc.SenseOrder)}"
             , "{nameof(Misc.Order)}"
             , "{nameof(Misc.TagName)}"
          FROM "{Schema}"."{nameof(Misc)}";

        INSERT INTO "{nameof(Note)}"
             ( "{nameof(Note.EntryId)}"
             , "{nameof(Note.SenseOrder)}"
             , "{nameof(Note.Order)}"
             , "{nameof(Note.Text)}")
        SELECT "{nameof(Note.EntryId)}"
             , "{nameof(Note.SenseOrder)}"
             , "{nameof(Note.Order)}"
             , "{nameof(Note.Text)}"
          FROM "{Schema}"."{nameof(Note)}";

        INSERT INTO "{nameof(PartOfSpeech)}"
             ( "{nameof(PartOfSpeech.EntryId)}"
             , "{nameof(PartOfSpeech.SenseOrder)}"
             , "{nameof(PartOfSpeech.Order)}"
             , "{nameof(PartOfSpeech.TagName)}")
        SELECT "{nameof(PartOfSpeech.EntryId)}"
             , "{nameof(PartOfSpeech.SenseOrder)}"
             , "{nameof(PartOfSpeech.Order)}"
             , "{nameof(PartOfSpeech.TagName)}"
          FROM "{Schema}"."{nameof(PartOfSpeech)}";

        INSERT INTO "{nameof(ReadingRestriction)}"
             ( "{nameof(ReadingRestriction.EntryId)}"
             , "{nameof(ReadingRestriction.SenseOrder)}"
             , "{nameof(ReadingRestriction.Order)}"
             , "{nameof(ReadingRestriction.ReadingText)}")
        SELECT "{nameof(ReadingRestriction.EntryId)}"
             , "{nameof(ReadingRestriction.SenseOrder)}"
             , "{nameof(ReadingRestriction.Order)}"
             , "{nameof(ReadingRestriction.ReadingText)}"
          FROM "{Schema}"."{nameof(ReadingRestriction)}";
        """;
}
